INSERT INTO medical.PersonalCare (Brand_name,Product_name,Description,Ingredients,`Type`,Price,Quantity) VALUES
	 ('Dettol','Dettol Skincare Handwash Pump','Dettol Skincare Handwash has a pH-balanced formula that keeps your hands hygienic and refreshed. Dettol handwash protects you from illness-causing germs and bacteria. It is a trusted brand that works like a barrier between your hands and illness-causing germs & bacteria. This hand wash contains glycerin, which keeps your hands moisturised and ensures proper hygiene.','Sodium Laureth SulphateGlycol DistearateGlycerin Sodium ChlorideAmmonium Lauryl SulphateMethyl chloroisothiazolinoneHexyl CinnamolCitronellolLimoneneBenzyl Salicylate','200 ml pump-bottle',96.30,89),
	 ('Johnson & Johnson','Johnson''s Baby Shampoo','Johnson''s Baby Shampoo is gentle on your baby''s eyes and keeps their hair soft and shiny. It is dermatologist-tested and free of parabens, phthalates, sulfates, and dyes, making it safe for daily use.','Water, Cocamidopropyl Betaine, PEG-80 Sorbitan Laurate, Sodium Trideceth Sulfate, PEG-150 Distearate, Fragrance, Tetrasodium EDTA, Quaternium-15, Citric Acid, Sodium Hydroxide','240 ml bottle',123.00,200),
	 ('Colgate','Colgate Total Toothpaste','Colgate Total Toothpaste fights germs for up to 12 hours and helps prevent plaque, tartar buildup, and cavities. It provides a fresh breath and leaves your mouth feeling clean and healthy.','Sodium Fluoride, Triclosan, Water, Hydrated Silica, Glycerin, Sorbitol, PVM/MA Copolymer, Sodium Lauryl Sulfate, Cellulose Gum, Flavor, Sodium Hydroxide','140 ml  tube',80.00,150),
	 ('Neutrogena','Neutrogena Hydro Boost Water Gel','Neutrogena Hydro Boost Water Gel is a hydrating gel moisturizer that instantly quenches dry skin and keeps it looking smooth, supple, and hydrated all day. It is oil-free and non-comedogenic.','Water, Dimethicone, Glycerin, Cetearyl Olivate, Sorbitan Olivate, Sodium Hyaluronate, Dimethicone/Vinyl Dimethicone Crosspolymer, Polyacrylamide, C13-14 Isoparaffin, Laureth-7, Carbomer','1.7 oz jar',299.00,80),
	 ('Dove','Dove Sensitive Skin Beauty Bar','Dove Sensitive Skin Beauty Bar is hypoallergenic and suitable for sensitive skin. It gently cleanses while nourishing your skin, leaving it soft and smooth. It is fragrance-free.','Sodium Lauroyl Isethionate, Stearic Acid, Sodium Tallowate or Sodium Palmitate, Lauric Acid, Sodium Isethionate, Water, Sodium Stearate, Cocamidopropyl Betaine','4 oz bar',110.00,120),
	 ('Gillette','Gillette Fusion5 ProGlide Razor','The Gillette Fusion5 ProGlide Razor features FlexBall technology for a close and comfortable shave. It has five anti-friction blades for a smooth glide, and the precision trimmer is perfect for shaping facial hair.','Lubrication Strip, Precision Trimmer, MicroComb, FlexBall Technology','Razor',99.00,50),
	 ('Old Spice','Old Spice Swagger Deodorant','Old Spice Swagger Deodorant provides long-lasting odor protection with a bold, masculine scent. It keeps you feeling fresh and confident all day.','Aluminum Zirconium Trichlorohydrex Gly, Fragrance','Deodorant',399.00,100),
	 ('Nivea Men','Nivea Men Sensitive Post Shave Balm','Nivea Men Sensitive Post Shave Balm soothes and moisturizes the skin after shaving. It is specially designed for sensitive skin and helps reduce irritation and redness.','Water, Glycerin, Isopropyl Palmitate, Chamomilla Recutita Flower Extract, Tocopheryl Acetate, Hamamelis Virginiana Bark/Leaf Extract','Aftershave',120.00,75),
	 ('American Crew','American Crew Fiber Hair Styling Cream','American Crew Fiber is a high-hold, low-shine hair styling cream that provides a matte finish. It helps thicken, texturize, and increase fullness to your hair.','Aqua, Lanolin Cera, Cetearyl Alcohol, PVP, SD Alcohol 40-B, Ceteareth-20, PEG-16 Macadamia Glycerides, Hydroxypropyl Guar','Hair Styling',900.00,60),
	 ('Dove','Dove Sensitive Skin Body Wash','Dove Sensitive Skin Body Wash is gentle on sensitive skin and provides nourishment and hydration. It leaves your skin feeling soft and refreshed without irritation.','Water, Glycerin, Cocamidopropyl Betaine, Sodium Cocoyl Glycinate, Sodium Lauroyl Isethionate, Sodium Chloride','Body Wash',401.00,80);
INSERT INTO medical.PersonalCare (Brand_name,Product_name,Description,Ingredients,`Type`,Price,Quantity) VALUES
	 ('Maybelline','Maybelline SuperStay Matte Lipstick','Maybelline SuperStay Matte Lipstick offers long-lasting, bold color that stays on for up to 16 hours. It provides a comfortable matte finish without drying out your lips.','Dimethicone, Bis-Diglyceryl Polyacyladipate-2, Hydrogenated Polyisobutene, Phenyl Trimethicone','Lipstick',1200.00,60),
	 ('TRESemmé','TRESemmé Moisture Rich Shampoo','TRESemmé Moisture Rich Shampoo is designed to deliver optimized hydration to dry and damaged hair. It leaves hair soft, shiny, and manageable.','Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Dimethiconol','Shampoo',40.00,90),
	 ('Olay','Olay Regenerist Micro-Sculpting Cream','Olay Regenerist Micro-Sculpting Cream is a moisturizer that helps reduce the appearance of fine lines and wrinkles. It hydrates and firms the skin for a youthful look.','Water, Glycerin, Isohexadecane, Niacinamide, Dimethicone','Face Cream',299.00,70),
	 ('Tampax','Tampax Pearl Tampons','Tampax Pearl Tampons provide up to 8 hours of leak-free protection. They have a smooth plastic applicator and a unique design for comfortable wear.','Rayon, Cotton, Polyester, Polyethylene, Polypropylene, Regenerated Cellulose','Feminine Hygiene',600.00,100),
	 ('Himalaya','Himalaya Neem Face Wash','Himalaya Neem Face Wash is a herbal cleanser that helps remove impurities and prevent acne. It contains neem and turmeric, known for their antibacterial properties.','Water, Ammonium Lauryl Sulfate, Cocamidopropyl Betaine, Glycerin, Neem Extract, Turmeric Extract','Cleanser',300.00,120),
	 ('Lotus Herbals','Lotus Herbals Safe Sun SPF 30 Matte Gel Sunscreen','Lotus Herbals Safe Sun SPF 30 Matte Gel Sunscreen provides broad-spectrum protection with a matte finish. It is suitable for oily and acne-prone skin.','Octyl Methoxy Cinnamate, Avobenzone, Zinc Oxide, Titanium Dioxide, Ethylhexyl Triazone','Sunscreen',90.00,77),
	 ('Biotique','Biotique Bio Dandelion Visibly Ageless Serum','Biotique Bio Dandelion Visibly Ageless Serum is a natural and organic anti-aging serum. It contains dandelion and nutmeg oil to help reduce the signs of aging.','Dandelion Extract, Baheda Extract, Nutmeg Oil, Lotion Base Q.S.','Serum',500.00,50),
	 ('Pond''s','Pond''s White Beauty BB+ Cream','Pond''s White Beauty BB+ Cream is a multi-purpose beauty cream that provides instant coverage, sun protection, and fairness benefits. It contains SPF 30 PA++.','Water, Cyclopentasiloxane, Ethylhexyl Methoxycinnamate, Glycerin, Titanium Dioxide','BB Cream',300.00,100),
	 ('Kaya','Kaya Skin Clinic Purifying Cleanser','Kaya Skin Clinic Purifying Cleanser is designed for acne-prone skin. It contains salicylic acid and tea tree oil to help cleanse and clear the skin.','Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Salicylic Acid, Tea Tree Oil','Cleanser',199.00,70),
	 ('Patanjali','Patanjali Aloe Vera Gel','Patanjali Aloe Vera Gel is a natural and Ayurvedic gel that helps moisturize and soothe the skin. It is enriched with the goodness of aloe vera.','Aloe Vera Gel, Base Material','Gel',99.00,150);
INSERT INTO medical.PersonalCare (Brand_name,Product_name,Description,Ingredients,`Type`,Price,Quantity) VALUES
	 ('Forest Essentials','Forest Essentials Soundarya Radiance Cream','Forest Essentials Soundarya Radiance Cream is a luxurious Ayurvedic cream that promotes skin radiance. It contains 24K gold bhasma and saffron for a glowing complexion.','24K Gold Bhasma, Saffron, Cow''s Ghee, Aloe Vera, Anantmool','Face Cream',68.00,40),
	 ('Kama Ayurveda','Kama Ayurveda Pure Rosewater','Kama Ayurveda Pure Rosewater is a natural toner and mist made from the steam distillation of rose petals. It refreshes and hydrates the skin.','100% Pure Steam Distilled Rose Water','Toner',35.00,90),
	 ('Vicco','Vicco Turmeric Cream','Vicco Turmeric Cream is an Ayurvedic skincare cream with the goodness of turmeric and sandalwood oil. It helps in skin protection and healing.','Water, Stearic Acid, Turmeric, Sandalwood Oil','Cream',119.00,80),
	 ('Baidyanath','Baidyanath Rhuma Oil','Baidyanath Rhuma Oil is an Ayurvedic oil for joint pain relief. It contains natural herbs and oils that help soothe and relax muscles and joints.','Mahamasha Taila, Tila Taila, Prasarini Taila, Vishagarbha Taila','Ayurvedic Oil',599.00,60);
